### Check Hs256 JWT Token
GET http://jwt-token-server.test/api/checkHs256
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5ZDU2MzE3MS02ZTBhLTQxODMtYjgxZi1iMTE5MmUzMzEyOGUiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzI5OTM1MjIyLCJleHAiOjE3Mjk5Mzg4MjIsImRhdGEiOm51bGx9.aBc0Efa21oTcnTwvsMoJvR5IQGEAR6FHDYy3TYxXn9E

### Check RS256
GET http://jwt-token-server.test/api/checkRs256
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI5ZDU4OTEwYS03NWY5LTRjOWYtOTgxNi0yNGRkZmNlNmE0MzkiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzMwMDM3MTYwLCJleHAiOjE3MzAwNDA3NjAsImRhdGEiOm51bGx9.bJbv4RPu2UN_v0Z0FNHmdoScMEQ4T9Hhk5ET-MmAeSb6MuGYJVTbaTV72HhSMZ284JONrKzGj0OkWzTL_ZHsPbPx_BtZZuQCaTqyO7hk8cxn_Jm6FUavjjEtb6DCrizW8h-WhEmo9mh720jVoP5eA5DgKtdLaOU1fPMxfB4ZFt5TDj0GquQbqOarzY2n5K7Rn9E0cD6oaHUQZwHGy4fp3i3HHmqAYC0hXuqsV4JXvJ4OkaBsrJA2gT062jrNNaWnMW79AZ11Rtzt3bdkjiSxESGFKMDJ5PgoZ-FpX6-0FJLk6Kr4PSMwBlBkh-kLv3gGxEuI2CRp6jmrPHm1kiCKig

### Check RS256 in Go
GET http://localhost:9090/verify
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI5ZDU4OTEwYS03NWY5LTRjOWYtOTgxNi0yNGRkZmNlNmE0MzkiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzMwMDM3MTYwLCJleHAiOjE3MzAwNDA3NjAsImRhdGEiOm51bGx9.bJbv4RPu2UN_v0Z0FNHmdoScMEQ4T9Hhk5ET-MmAeSb6MuGYJVTbaTV72HhSMZ284JONrKzGj0OkWzTL_ZHsPbPx_BtZZuQCaTqyO7hk8cxn_Jm6FUavjjEtb6DCrizW8h-WhEmo9mh720jVoP5eA5DgKtdLaOU1fPMxfB4ZFt5TDj0GquQbqOarzY2n5K7Rn9E0cD6oaHUQZwHGy4fp3i3HHmqAYC0hXuqsV4JXvJ4OkaBsrJA2gT062jrNNaWnMW79AZ11Rtzt3bdkjiSxESGFKMDJ5PgoZ-FpX6-0FJLk6Kr4PSMwBlBkh-kLv3gGxEuI2CRp6jmrPHm1kiCKig
