### Check Hs256 JWT Token with SimpleJwt
GET http://jwt-token-server.test/api/simplejwt/checkHs256
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6bnVsbH0.eyJqdGkiOiI5ZDVhNWY2My03ZWRmLTQyN2MtOWFkNC1jNzU1NmM1NDFjYTAiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzMwMTE0NzI5LCJleHAiOjE3MzAxMTgzMjksImRhdGEiOm51bGx9.cEnGsbccZBbL8Z2tEB1CAqjwo5lvTe9oySXESaoJHeM

### Check RS256 JWT Token with SimpleJwt
GET http://jwt-token-server.test/api/simplejwt/checkRs256
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6bnVsbH0.eyJqdGkiOiI5ZDVhNWY2My03ZWRmLTQyN2MtOWFkNC1jNzU1NmM1NDFjYTAiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzMwMTE0NzI5LCJleHAiOjE3MzAxMTgzMjksImRhdGEiOm51bGx9.qN9-22VvWVUcHIkR5nZYMCm9_sxgI2Gs2s6PaWAiafYliXH9pyH_9FeGxRXfPo9SsvZglpuOTcqEcxWJEsNOqGcXVBS8JKzTuNIlrSkb8j_2mNrTi6fzRHZemPKQ3DSfMFPiRAu6L21uk3BOMijxoPBPfGNXfkBN9yc8AlV143jvUJx5LTzUHLivWS4Ztm0pEF3R2B9Y5p_YDH2v4q-amWP9C1nQwpW6n44YupYJ0g6FISXpseXpLBGEXAo4jwICHc1wWje6vXkDIXzIJsXilo-mD7heZcG6yUt3-cpFBuIzsfu1PQRl5PzytyfE93fBS7YlEqqc9sXth7awJO6sMQ

### Check ES256 JWT Token with SimpleJwt
GET http://jwt-token-server.test/api/simplejwt/checkEs256
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6bnVsbH0.eyJqdGkiOiI5ZDVhYTcwZC1kOWIwLTRmM2YtYTFhMC01NmY1ZTc1NGIyYjkiLCJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaXNzIjoiaHR0cDpcL1wvand0LXRva2VuLXNlcnZlci50ZXN0IiwiaWF0IjoxNzMwMTI2NzUzLCJleHAiOjE3MzAxMzAzNTMsImRhdGEiOm51bGx9.BzjOw5v1NgVbVv9mbLBsaU7NcLfUqbVEJ7o335kpPPNeIlt9SAXaiCiJ1kD6nFQ1D-Igrg-T_M5zhK87aOLGIQ
